import streamlit as st
from PIL import Image


def show_home_page():
    """
    This function displays the Home Page.
    """

    st.header("Identifying duplicate question pairs on Quora")
    st.text("")
    st.text("")
    img = Image.open("quora_home.jpg")
    st.image(img, caption="Credits: time.com")
    st.text("")

    st.caption("### **OVERVIEW :**")
    st.markdown("""People ask a lot of random questions. How long do sea turtles live? How many kilometers are in a mile?
                Who is the king of Sweden? Nowadays, when a question pops into your head, the very first place you go to
                is the 'internet'. There are a bunch of Q&A platforms you can refer to when looking for any information,
                one of them being **[Quora](https://www.quora.com/)**.
                Quora is a question-and-answer platform where people go & find information. Every piece of content on
                the site is generated by users, meaning it is created, edited, and organized by the same people that use
                the website. When a user posts a question, other users with expertise or interest in the subject can
                reply. Users then upvote and downvote answers to surface the most informative and relevant response.
                After hearing that description of Quora, you might be thinking, “Why don’t I just use an everyday
                search engine?” Well, Quora has some qualities that other research tools don’t.
              """)
    st.markdown("* It allows users to create social networks and follow topics that interest them.")
    st.markdown("* It focuses on high-quality questions and answers.")
    st.markdown("* It lets users vote on answers to highlight the most accurate information possible.")
    st.markdown("* It's free!")
    st.markdown("""According to the now defunct Alexa popularity ranking, in **February 2022**, Quora was ranked **#276** in
                   traffic out of all sites in the **U.S.** and ranked as the top **#323** site globally. This five-year Google
                   Trends data shows that Quora has an upward trending profile. That upward trend is not limited to the
                   United States alone, it’s also reflected in **France, German, Canada, U.K., and Australia**. 
                """)
    st.text("")
    img = Image.open("quora_popularity.png")
    st.image(img, caption="Credits: Google Trends")
    st.divider()

    st.caption("### **OBJECTIVE :**")
    st.markdown("""We need to build a machine learning model that **identifies which of the questions asked on Quora are
                   duplicates of the questions that have already been asked**. This could be useful to instantly provide
                   answers to questions that have already been answered.
                """)
    st.divider()

    st.caption("### **BUSINESS CONSTRAINTS :**")
    st.markdown("""* **Interpretability of the model is partially important** because a user doesn't need to know why
                   the model has assigned a specific class to the given data point.
                """)
    st.markdown("""* There are **no low-latency requirements** but at the same time, we also don't want our latency to
                   be in several minutes.
                """)
    st.markdown("* **Errors must be minimized** since, incorrect predictions can impact user experience on Quora.")
    st.markdown("""* The model should return a **probability of the data point belonging to a class** rather than
                   simply returning a class so that we can choose any threshold of choice.
                """)
    st.divider()

    st.caption("### **MAPPING THE PROBLEM TO A MACHINE LEARNING PROBLEM :**")
    st.markdown("""* For a given pair of questions we need to predict if they are duplicate or not. It is a **binary
                   classification problem**.
                """)
    st.markdown("""* **Performance metric :** Log-loss, Binary confusion matrix (We have chosen Log-loss because it uses
                   the actual probability values which is our business constraint.)
                """)
    st.divider()

    st.caption("### **DATA DESCRIPTION :**")
    st.markdown("You can download the dataset from ***[here](https://www.kaggle.com/c/quora-question-pairs/data)***")
    st.markdown("We have 2 data files :")
    st.markdown("* **train.csv.zip**")
    st.markdown("* **test.csv.zip**")
    st.markdown("Size of train.csv: **60.4 MB** (unzipped)")
    st.markdown("Size of test.csv: **314.02 MB** (unzipped)")
    st.markdown("Number of rows in train.csv: **404,290**")
    st.markdown("Data file's information :")
    st.markdown("""* **train.csv** : A comma separated file containing the description of questions used for training.
                Fields are **'id'** (the id of a training set question pair), **'qid1, qid2'** (unique ids of each
                question; only available in train.csv), **'question1, question2'** (the full text of each question),
                **'is_duplicate'** (the target variable, set to 1 if question1 and question2 have essentially the same
                meaning, and 0 otherwise.)
                """)
    st.markdown("""* **test.csv** : A comma separated file containing the description of questions used for evaluation.
                Fields are **'test_id'** (the id of a testing set question pair),
                **'question1, question2'** (the full text of each question),
                """)
    st.divider()

    st.markdown("""***LIBRARIES : `base64`, `matplotlib`, `numpy`, `pandas`, `pickle`, `PIL`,
                    `re`, `scikit-learn`, `scipy`, `seaborn`, `streamlit`***""")